### ISSUE TITLE
Clerk TOC flashes "project" on page load

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#269]
This is on the latest Clerk on Clojars. I see this when I refresh the page with the TOC out.

![2022-11-08 13 56 02](https://user-images.githubusercontent.com/69635/200673561-1fbd6bfe-80c3-4b2b-83bd-6838565ae975.gif)

**Comment by joe-loco** [comment]
Thanks for the report! This is fixed now.

**Comment by sritchie** [comment]
Thank you!

**Comment by sritchie** [comment]
Hey @joe-loco , I'm reopening since this is still happening on mobile devices; when I load https://mathbox.mentat.org/dev/mathbox/examples/math/pq_knot.html, the table of contents is expanded and then shrinks back down only after load.

**Comment by joe-loco** [comment]
@sritchie This should be fixed now.
